###
GET http://localhost:8080/contacts

###
POST http://localhost:8080/contacts 
Content-Type: application/json

    {
      "Name":"peugeot 304",
      "Miles_per_Gallon":30,
      "Cylinders":4,
      "Displacement":79,
      "Horsepower":70,
      "Weight_in_lbs":2074,
      "Acceleration":19.5,
      "Year":"1971-01-01",
      "Origin":"Europe"
    }

###
PUT http://localhost:8080/contacts/646d45e692db183a7302e51b
Content-Type: application/json

    {
      "Name":"volkswagen model 111",
      "Miles_per_Gallon":27,
      "Cylinders":4,
      "Displacement":97,
      "Horsepower":60,
      "Weight_in_lbs":1834,
      "Acceleration":19,
      "Year":"1971-01-01",
      "Origin":"Europe"
    }

###
DELETE http://localhost:8080/contacts/646d45e692db183a7302e51b

###
GET http://localhost:8080/contacts/646d3e16b9c6a9e4353d97b8

###
GET http://localhost:8080/contacts/646d3e65b9c6a9e4353d97bb

###
GET http://localhost:8080/contacts/646d3e79b9c6a9e4353d97bc

###
GET https://cse341huang-week5.onrender.com/contacts